### ISSUE TITLE
IsMarginVisible does not appear to be available via the new WithAxis methods

### ISSUE THREAD

**Issue by xdaDaveShaw** [fsharp/FSharp.Charting#60]
I could not find a way to change the visibility of Margins on the charts I were creating leading to some funny looking charts:

![so](https://cloud.githubusercontent.com/assets/2511715/5538198/3ab4cb46-8aa7-11e4-9400-0189ebf57386.png)

Looking at the history of FSharp.Charting.fs this has been this way since the file was created in commit [580e694f](https://github.com/fsharp/FSharp.Charting/commit/580e694fb6e6d7ddc1822350e3f74c1cf0b45603).

It looks like it can be uncommented without any problems. I'll submit a PR for it soon.

**Comment by dsyme** [comment]
Fixed in https://github.com/fsharp/FSharp.Charting/pull/61
