### ISSUE TITLE
Linear regression

### ISSUE THREAD

**Issue by forki** [fsharp/FSharp.Charting#62]
Is it possible to plot something like:

![image](https://cloud.githubusercontent.com/assets/57396/5633167/f16787e2-95d4-11e4-8257-dc3e8dbfb940.png)

**Comment by tpetricek** [comment]
You'd have to calculate the linear regression yourself - but with that, you could use Chart.Line and Chart.Points and combine them using Chart.Combine.

**Comment by forki** [comment]
I have the linear regression. I wonder how to create the chart.

**Comment by tpetricek** [comment]
Given a list of X*Y pairs called `data`, something (roughly) like this should do the trick:

    let a, b = linearRegression data
    let minx, maxx = data |> Seq.minBy fst, data |> Seq.maxBy fst   
    Chart.Combine
      [ Chart.Line [ (minx, a*minx+b); (maxx, a*maxx+b) ]
        Chart.Point data ]

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/5643618/f6d5f052-965a-11e4-9e14-d88ec91da59b.png)

:+1:
